# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Setup
title: "Listening in/to South Florida"
publisher: "English and MLL UMiami"
description: "Digital Environmental Humanities Project"

# PROD
url: "http://rm4-25.github.io/FL-Sounds2/"
baseurl: ""
future: True
incremental: False

# Misc

githuburl: "http://rm4-25.github.io/FL-Sounds2/"
